# 1 Basics

Reading info from a file

In [1]:
import numpy as np
a= np.loadtxt("values.txt",float)
print(a)

[[1. 2. 3. 4.]
 [4. 4. 3. 6.]
 [4. 9. 9. 9.]]


Arithmetic with arrays

In [2]:
a = np.array([1,2,3,4],int)
b = 2*a
print(a)
print(b)
print(b+1)
print(b*a)
print(np.dot(a,b))

[1 2 3 4]
[2 4 6 8]
[3 5 7 9]
[ 2  8 18 32]
60


In [3]:
a= np.array([[1,3],[2,4]],int)
b = np.array([[4,-2],[-3,1]])
c = np.array([[1,2],[2,1]])
print(np.dot(a,b)+2*c)

[[-3  5]
 [ 0  2]]


In [4]:
import math
a=np.array([2,3,4,5])
b = np.array(list(map(math.sqrt,a)),float)
print(b)

[1.41421356 1.73205081 2.         2.23606798]


In [5]:
# average of a set of values in a file

values= np.loadtxt("values.txt",float)
mean = sum(values)/len(values)
# hace los promedios verticales
print(values)
print(mean)

[[1. 2. 3. 4.]
 [4. 4. 3. 6.]
 [4. 9. 9. 9.]]
[3.         5.         5.         6.33333333]
